export const products = [
    {
      coverImage:'../../assets/img/Unknown.png',
      name:'aaaa',
      price:1004,
      description:'bbb',
      heading1:'afdsafjiaofjowaejfo',
      heading2:'aaaaafdsafjiaofjowaejfo',
      heading3:'afdsaaaaaafjiaofjowaejfo'
    },
    {
      coverImage:'./assets/img/phone-cover.jpg',
      name:'ccbc',
      price:1003,
      description:'dddd',
      heading1:'afdsafjiaofjowaejfo',
      heading2:'aaaaafdsafjiaofjowaejfo',
      heading3:'afdsaaaaaafjiaofjowaejfo'
    },
    {
      coverImage:'./assets/img/phone-cover.jpg',
      name:'eeee',
      price:1002,
      description:'dfddd',
      heading1:'afdsafjiaofjowaejfo',
      heading2:'aaaaafdsafjiaofjowaejfo',
      heading3:'afdsaaaaaafjiaofjowaejfo'
    },
    {
      coverImage:'./assets/img/phone-cover.jpg',
      name:'ffff',
      price:1001,
      description:'fsa',
      heading1:'afdsafjiaofjowaejfo',
      heading2:'aaaaafdsafjiaofjowaejfo',
      heading3:'afdsaaaaaafjiaofjowaejfo'
    }
  ];
  